name: stemxploref2
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3
  shared_preferences: ^2.2.2
  flutter_slidable: ^3.1.0
  provider: ^6.1.1
  curved_navigation_bar: ^1.0.6
  flutter_localization: ^0.3.3
  video_player: ^2.8.1
  chewie: ^1.8.1
  http: ^1.2.0
  confetti: ^0.7.0
  audioplayers: ^5.2.1
  sqflite: ^2.3.0
  path: ^1.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: false
  uses-material-design: true

  assets:
    - assets/images/Logo_F2_2.png
    - assets/icons/1.png
    - assets/icons/2.png
    - assets/icons/3.png
    - assets/icons/4.png
    - assets/icons/5.png
    - assets/icons/6.png
    - assets/flag/language uk_flag.png
    - assets/flag/language ms_flag.png
    - assets/textbook/ASK/BC_ASK.jpg
    - assets/textbook/RBT/BC_RBT.jpg
    - assets/textbook/Science/BC_Science.jpg
    - assets/textbook/Mathematics/BC_Mathematics.jpg
    - assets/images/STEMvideo1.png
    - assets/images/nutrition.png
    - assets/images/biodiversity.png
    - assets/images/ecosystem.png
    - assets/images/Logo_Kedah.png
    - assets/images/Logo_UUM.png
    - assets/audio/quiz_bm.music.mp3
    - assets/stem_info/images/
    - assets/stem_info/videos/


